#!/bin/bash
clear

echo La cuenta actual es:
git config user.name
git config user.email
echo
echo

options (){
echo ================================
echo "s = Salir | c = Ver Cuenta Actual | l = Listar Perfiles | h = Ayuda"
echo "______________________________"
echo
}

list (){
echo 1 = "frankwmm (gmail)"
echo 2 = "frankmwilsonm (upeu)"
echo 3 = "LFrakie (hmail)"
}

options
list
echo
 
ac (){
echo ingrese option:
read num

case $num in
s)
clear
echo exit gitac
exit 0
;;

o)
list
options
ac
echo
echo
;;

c)
clear
echo la cuenta actual es:
git config user.name
git config user.email
echo
echo
options
ac
;;

l)
clear
echo 1 = "frankwmm (gmail)"
echo 2 = "frankmwilsonm (upeu)"
echo 3 = "LFrakie (hmail)"
echo
echo
options
ac
echo
;;

1)
clear
git config --global user.name frankwmm
git config --global user.email frankwilsonknow@gmail.com
echo Cambiaste cuenta GIT a frankwmm
echo Validando...
echo ==========
git config user.name
git config user.email
echo ==========
echo
echo
options
ac
;;

2)
clear
git config --global user.name frankmwilsonm
git config --global user.email frank.mamani@upeu.edu.pe 
echo Cambiaste cuenta GIT a frankmwilsonm
echo Validando...
echo ==========
git config user.name
git config user.email
echo ==========
echo
echo
options
ac
;;

3)
clear
git config --global user.name LFrakie
git config --global user.email randymas15@hotmail.com
echo Cambiaste cuenta GIT a LFrakie
echo Validando...
echo ==========
git config user.name
git config user.email
echo ==========
echo
echo
options
ac
;;

*)
clear
(echo -e "Algo salio mal vuelve a intentar otra opción :c\n"; echo -e "------------------------\n"; echo -e "s = Salir | c = Ver Cuenta Actual | l = Listar Perfiles | h = Ayuda\n"; echo -e "------------------------\n"; echo -e "1 = frankwmm (gmail)\n"; echo -e "2 = frankmwilsonm (upeu)\n"; echo -e "3 = LFrakie (hmail)") \
| cowthink -W80
echo
echo
ac
;;
esac

}
ac

