#!/bin/bash

echo
echo -e "\033[30;42m Iniciando y Añadiendo Nuevo Repo: \033[0m"
git init && git add .

echo
echo -e "\033[30;42m Repo Create and Conect: \033[0m"
gh repo create

echo
echo -e "\033[30;42m Commit Ur Code: \033[0m"
git commit -m "start and conect project/git-start"

echo
echo -e "\033[30;42m Up Ur Code To MASTER Branch \033[0m"
git push -u origin master

echo
echo -e "\033[37;44m Link Del Repositorio: \033[0m"
git config --get remote.origin.url
echo
