#!/bin/bash

echo "=============================="
echo "Agregando todos los cambios"
echo "=============================="

git add .

echo "Agregar Commit: "

read varcommit

#echo It\'s nice to meet you $varcommit

git commit -m "$varcommit"

echo "Branch to Push: "

read varbranch
git push -u origin $varbranch 
