#!/bin/bash
echo ""

echo "=============================="
echo -e "\e[0;32m Agregando todos los cambios \e[0m"
echo "=============================="

git add .

echo -e "\033[37;44m Agregar Commit: \033[0m"
read varcommit
git commit -m "$varcommit /git-up"

echo ""

echo -e "\033[30;42m Branch to Push: \033[0m"
read varbranch
echo "Haciendo Push..."

echo "========================"
git push -u origin $varbranch

echo "========================"

echo ""
